### ISSUE TITLE
mostCommon on unique array?

### ISSUE THREAD

**Issue by Tjorriemorrie** [willkurt/ID3-Decision-Tree#1]
Hi, this is awesome work; really impressive. I'm busy rewriting it over to another language and got bamboozled by the mostCommon on the unique array.

```
var mostCommon = function(l){
   return _.sortBy(l,function(a){
        return count(a,l);
    }).reverse()[0];
}
```

From what I can gather, the count will be 1 for all of them? 

```
if(features.length == 0){
        console.log("returning the most dominate feature!!!");
        var topTarget = mostCommon(targets);
        return {type:"result", val: topTarget, name: topTarget, alias: topTarget+randomTag()};
    }
```

Should the unique only be used where you check for the length?

```
var targets = _.unique(_s.pluck(target));
    if (targets.length == 1){
```

**Comment by willkurt** [comment]
I believe you are correct about this,  sorry that I've been so slow to respond. I'll fix this when I find some time, or you can feel free to put in a PR anytime. Thanks!

**Comment by willkurt** [comment]
Okay that should be fixed. Sorry about the insane wait time on that ;)
