### ISSUE TITLE
Demo no longer works due to mixed active content protections

### ISSUE THREAD

**Issue by christopherliu** [willkurt/ID3-Decision-Tree#4]
Hello! Can you update the demo at https://willkurt.github.io/ID3-Decision-Tree/ to use HTTPS links to scripts? Browsers now block mixed active content (https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content?utm_source=mozilla&utm_medium=firefox-console-errors&utm_campaign=default)

Thanks!

**Comment by willkurt** [comment]
Thanks so much for noticing this and also doing most of the work in debugging this issue! The fix should be up now.
